version: 2
jobs:
  build:
    working_directory: ~/aaronshaf/dynamodb-admin
    parallelism: 1
    # To see the list of pre-built images that CircleCI provides for most common languages see
    # https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:8-stretch-browsers
    steps:
      - checkout
      # Restore the dependency cache
      - restore_cache:
        keys:
          # This branch if available
          - v1-dep-{{ .Branch }}-
          # Default branch if not
          - v1-dep-master-
          # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
          - v1-dep-
    # The following line was run implicitly in your 1.0 builds based on what CircleCI inferred about the structure of your project. In 2.0 you need to be explicit about which commands should be run. In some cases you can discard inferred commands if they are not relevant to your project.
      - run: if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
      - run: export PATH="~/aaronshaf/dynamodb-admin/node_modules/.bin:$PATH"
      - run: npm install
      # Save dependency cache
      - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
          # This is a broad list of cache paths to include many possible development environments
          # You can probably delete some of these entries
          - vendor/bundle
          - ~/virtualenvs
          - ~/.m2
          - ~/.ivy2
          - ~/.bundle
          - ~/.go_workspace
          - ~/.gradle
          - ~/.cache/bower
          - ./node_modules
      - run: npm test
      # Save test results
      - store_test_results:
        path: /tmp/circleci-test-results
